### ISSUE TITLE
Can't decrypt bytes which encrypted by Python eexta extension

### ISSUE THREAD

**Issue by imagebreaker** [xxtea/xxtea-c#1]
I had encrypted some bytes with Python xxtea extension([https://pypi.python.org/pypi/xxtea/0.2.0](url)), but could not be decrypted by this algorithm. I checked the code between them, but still can't find the problem.

**Comment by imagebreaker** [comment]
I'm sorry for my carelessness, I reviewed both two pieces of codes and found that Python's was wrong.

**Comment by andot** [comment]
https://github.com/xxtea/xxtea-python

**Comment by imagebreaker** [comment]
Thank you so much for providing Python implementation! @andot

**Comment by imagebreaker** [comment]
What about making your xxtea algorithm support pkcs#7 padding?
