### ISSUE TITLE
对二进制的文件的加密不支持

### ISSUE THREAD

**Issue by little-tomato** [xxtea/xxtea-c#6]
我们打算使用xxtean对java的class文件进行加解密，由于class文件里面包含很多空的字符串。目前感觉是不支持的，请问啥时候能修复这个问题？

**Comment by andot** [comment]
有空字符串也支持，参数里面不是有长度吗？

**Comment by little-tomato** [comment]
我的测试代码是这样的，然后发现class文件里面前32个字符加密后再解密对应不上。比如原来的class文件前四位是16进制的：cafebabe,加密解密后都变成0。
        FILE *fid;
	fid = fopen("/root/Crypto.class","rb");
	if(fid == NULL)
	{
		printf("读取文件出错");
		return;
        }
       //获取文件大小
	fseek (fid , 0 , SEEK_END);       
	long size = ftell (fid);  
	rewind (fid); 
	//开辟存储空间
	int num = size/sizeof(char);
	unsigned char *pos = (unsigned char*) malloc (sizeof(unsigned char)*num);  
	if (pos == NULL)  
	{  
		printf("开辟空间出错");   
		return; 
	} 
	fread(pos,sizeof(char),num,fid);
	int i = 0;
    for(i = 0; i < num; i++)
	printf("%x\n", pos[i]);
	free(pos);     //释放内存
	fclose(fid);
       const unsigned char *text = pos;
    const char *key = "1234567890";
    size_t len;
    unsigned char *encrypt_data = xxtea_encrypt(text, num, key, &len);
    char * base64_data = base64_encode(encrypt_data, len);
    printf("%s\n", base64_data);
    unsigned char *decrypt_data = xxtea_decrypt(encrypt_data, len, key, &len);
    for(i = 0; i < num; i++)
    printf("%x\n",decrypt_data[i]);

    if (strncmp(text, decrypt_data, len) == 0) {
        printf("success!\n");
    }
    else {
        printf("fail!\n");
    }
    free(encrypt_data);
    free(decrypt_data);
    free(base64_data);
    return 0;

**Comment by little-tomato** [comment]
能否给我给联系方式深入交流下，我把字节码文件发你。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月23日(星期三) 下午2:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xxtea/xxtea-c] 对二进制的文件的加密不支持 (#6)





 
有空字符串也支持，参数里面不是有长度吗？

**Comment by andot** [comment]
你在赋值 text 之前，pos都让你给 free 了，后面操作的是无效内存区域，跑出什么结果都是正常的。

**Comment by little-tomato** [comment]
我该怎么写呢，c++我是现学现卖的。

**Comment by little-tomato** [comment]
搞定了。非常感谢。
