### ISSUE TITLE
不支持4个字节加解密，最少4个字节以上才可以，

### ISSUE THREAD

**Issue by niurenyige** [xxtea/xxtea-c#7]
static uint32_t * xxtea_uint_encrypt(uint32_t * data, size_t len, uint32_t * key) {
    uint32_t n = (uint32_t)len - 1;
    uint32_t z = data[n], y, p, q = 6 + 52 / (n + 1), sum = 0, e;

    if (n < 1) return data;

**Comment by andot** [comment]
支持的，在加密之前会把原始的字节数据转化为 uint32_t 数组，在转化过程中会增加一个用来表示长度的值，而恰好可以把少于4个字节的数据转化为2个元素的 uint32_t 数组。
